// @flow

export const RESTORED_DASHBOARD = 'RESTORED_DASHBOARD'
export const RESTORED_LOGIN = 'RESTORED_LOGIN'
export const RESTORED_SETTINGS = 'RESTORED_SETTINGS'
export const CONFIGURATIONS_REQUESTED = 'CONFIGURATIONS_REQUESTED'
export const CONFIGURATIONS_RESPONDED = 'CONFIGURATIONS_RESPONDED'
